CMAKE_MINIMUM_REQUIRED(VERSION 3.12)

PROJECT(http)

INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR} ${PROJECT_SOURCE_DIR}/vendor/asio/include)

FIND_PACKAGE(Threads REQUIRED)

SET(DEFAULT_BUILD_TYPE "Release")
IF(NOT CMAKE_BUILD_TYPE)
    MESSAGE(STATUS "No build type specified, defaulting to ${DEFAULT_BUILD_TYPE}")
    SET(CMAKE_BUILD_TYPE "${DEFAULT_BUILD_TYPE}")
ENDIF()
SET(CMAKE_CXX_STANDARD 20)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)

IF(CMAKE_BUILD_TYPE MATCHES Debug)
    IF("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
        MESSAGE("Debug mode, enable gcov")
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fprofile-arcs -ftest-coverage")
        SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fprofile-arcs -ftest-coverage")
        SET(LINK_LIBS "gcov")
    ENDIF()

    ADD_SUBDIRECTORY(vendor/googletest)
    ADD_SUBDIRECTORY(test)
ENDIF(CMAKE_BUILD_TYPE MATCHES Debug)

ADD_SUBDIRECTORY(examples)
